### ISSUE TITLE
fix: Favorites are not in sync with the schedule

### ISSUE THREAD

**Issue by Hannnes1** [felangel/flutter_and_friends#12]
**Description**

A few days ago I marked some items as favorites (The check-in on September 2:nd for example). After updating the app, some items were slightly changed and they seemed to be unfavoritized in the schedule. The old item still remained on the favorites tab though, so marking the new item as a favorite resulted in duplicates.

**Steps To Reproduce**

1. Mark an item as favorite
2. Change an item and update the app (not sure if a shorebird code push is required to see the bug)
4. See desynchronized state

**Expected Behavior**

A change in the schedule should be reflected in the favorites.

**Screenshots**

![Screenshot_20240901-082616.png](https://github.com/user-attachments/assets/535611ee-34ff-442e-ad31-b7abb481f82f)

![Screenshot_20240901-082629.png](https://github.com/user-attachments/assets/acb033ee-715d-4b90-9666-22d0938e8b59)

**Comment by felangel** [comment]
Thanks for reporting this! I'll get a fix out shortly 👍

**Comment by felangel** [comment]
This should be closed as part of https://github.com/felangel/flutter_and_friends/commit/90e34934f0e7de02cccc814400fa7f635d2bd930
