### ISSUE TITLE
App crashes/closes on fast scroll up (1.0.1 (9) #2)

### ISSUE THREAD

**Issue by aryehof** [felangel/flutter_and_friends#6]
iPad Air (3rd generation)
IPadOS 17.5.1

Occurs always. Just installed the app and had just restarted after prompt for update.

**Comment by felangel** [comment]
Thanks for filling an issue! This is related to https://github.com/shorebirdtech/shorebird/issues/2219 which we’re actively working to resolve. I’ll revert the patch tomorrow and apologize for the inconvenience!

**Comment by felangel** [comment]
Just pushed a patch to fix this in Flutter & Friends. Closing for now since the real issue is being tracked in the shorebird repo, thanks!
