### ISSUE TITLE
feat: New Puzzle Feature for Flutter & Friends 2024

### ISSUE THREAD

**Issue by jisjoe** [felangel/flutter_and_friends#8]
**Description**

Introduce an engaging new puzzle feature for the Flutter & Friends 2024 event. This feature includes:

Question Types:

- Matching
- Single-choice
- Fill-in-the-blanks

Features:

- Ability to set time limits for questions.
- Option to unlock questions as participants progress.
- A leaderboard to track and display participants' scores.

Technical Details:

- The quiz questions and submission process are managed by our custom-built API.
- The front end will showcase custom Rive animations and audio playback to enhance the user experience.

**Requirements**

- [ ] Implement matching, single-choice, and fill-in-the-blanks question types.
- [ ] Add functionality to set time limits for each question.
- [ ] Implement the question unlocking mechanism.
- [ ] Develop a leaderboard to display participant scores.
- [ ] Integrate the custom-built API for managing questions and submissions.
- [ ] Incorporate custom Rive animations.

**Additional Context**
<img src="https://github.com/user-attachments/assets/fc1d7b69-e939-4cdd-a0bc-98aadd52fe99" width="300px">

**Comment by spydon** [comment]
@felangel we discussed this with @jisjoe, he's adding some form of non-intrusive quiz game to the app.
I haven't looked at the code anything though.

**Comment by felangel** [comment]
Thanks so much! I'll do my best to review and get this merged sometime this week 🎉

**Comment by felangel** [comment]
@spydon @jisjoe I left my comments and some concerns at #9. Let me know what you think, thanks!

**Comment by felangel** [comment]
Closing this since I'm planning to release the changes in #11 as part of the next release 🎉
